print("Program starting.")
brand = input("Insert car brand: ")
model = input("Insert car model: ")
print("Car brand is", brand, sep=' "', end='" ')
print('and the model is', model, sep=" '", end="' ",)
print("\nProgram ending.")